import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "What Is CAC Payback Period in Ecommerce?",
  description:
    "CAC payback period is the time it takes for the contribution generated by a new customer to recover the amount spent acquiring that customer. A worked example.",
  alternates: { canonical: "https://www.attribix.app/resources/cac-payback-period-ecommerce" },
  openGraph: {
    title: "What Is CAC Payback Period in Ecommerce?",
    description: "LTV can make acquisition look profitable while hiding how much cash is tied up during growth. Payback shows the truth.",
    url: "https://www.attribix.app/resources/cac-payback-period-ecommerce",
    images: [{ url: "/og-image.png", width: 1200, height: 630, alt: "Attribix" }],
  },
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
