"use client";

import Link from "next/link";
import ProductPageShell from "@/components/marketing/ProductPageShell";
import { Reveal } from "@/components/marketing/Reveal";
import Eyebrow from "@/components/marketing/Eyebrow";
import Breadcrumbs from "@/components/marketing/Breadcrumbs";
import { ManagedServicesCTA } from "@/components/marketing/CTAGroup";

const ARTICLE_JSON_LD = {
  "@context": "https://schema.org",
  "@type": "Article",
  headline: "What Is CAC Payback Period in Ecommerce?",
  description: "CAC payback period is the time it takes for the contribution generated by a new customer to recover the amount spent acquiring that customer.",
  datePublished: "2026-08-12",
  dateModified: "2026-08-12",
  author: { "@type": "Organization", name: "Attribix", url: "https://www.attribix.app" },
  publisher: { "@type": "Organization", name: "Attribix", url: "https://www.attribix.app", logo: { "@type": "ImageObject", url: "https://www.attribix.app/assets/logo.svg" } },
  mainEntityOfPage: { "@type": "WebPage", "@id": "https://www.attribix.app/resources/cac-payback-period-ecommerce" },
};

const BREADCRUMB_JSON_LD = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    { "@type": "ListItem", position: 1, name: "Home", item: "https://www.attribix.app" },
    { "@type": "ListItem", position: 2, name: "Resources", item: "https://www.attribix.app/resources" },
    { "@type": "ListItem", position: 3, name: "CAC payback period", item: "https://www.attribix.app/resources/cac-payback-period-ecommerce" },
  ],
};

export default function Page() {
  return (
    <ProductPageShell>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(ARTICLE_JSON_LD) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(BREADCRUMB_JSON_LD) }} />

      {/* HERO */}
      <section className="mx-auto max-w-3xl px-4 pt-24 pb-10 md:pt-32">
        <Reveal>
          <Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Resources", href: "/resources" }, { label: "CAC payback period" }]} />
          <Eyebrow>Email &amp; Retention</Eyebrow>
          <h1 className="text-4xl sm:text-5xl md:text-6xl font-extrabold leading-[1.08] tracking-tight">
            What is CAC payback period in ecommerce?
          </h1>
          <p className="mt-6 text-lg text-white/65 max-w-xl leading-relaxed">
            CAC payback period is the time it takes for the contribution
            generated by a new customer to recover the amount spent
            acquiring that customer.
          </p>
        </Reveal>
      </section>

      {/* SIMPLE EXAMPLE */}
      <section className="mx-auto max-w-3xl px-4 py-10">
        <Reveal>
          <h2 className="text-2xl md:text-3xl font-extrabold mb-4">Simple example</h2>
          <div className="space-y-4 text-white/60 leading-relaxed text-sm">
            <p>CAC = $60.</p>
            <p>First order contributes $35 after variable costs.</p>
            <p>Second order two months later contributes another $30.</p>
            <p>
              The customer crosses $60 cumulative contribution after the
              second order. Payback is roughly two months.
            </p>
          </div>
        </Reveal>
      </section>

      {/* WHY IT MATTERS */}
      <section className="relative py-10">
        <div className="absolute inset-0 -z-10 bg-black/15" />
        <div className="mx-auto max-w-3xl px-4">
          <Reveal>
            <h2 className="text-2xl md:text-3xl font-extrabold mb-4">Why it matters</h2>
            <p className="text-white/60 leading-relaxed text-sm max-w-2xl">
              LTV can make acquisition look profitable while hiding how much
              cash is tied up during growth. Payback shows how quickly the
              business can recycle acquisition investment.
            </p>
          </Reveal>
        </div>
      </section>

      {/* CONTRIBUTION NOT REVENUE */}
      <section className="mx-auto max-w-3xl px-4 py-10">
        <Reveal>
          <h2 className="text-2xl md:text-3xl font-extrabold mb-4">Calculate contribution, not revenue</h2>
          <p className="text-white/60 leading-relaxed text-sm max-w-2xl">
            A $100 repeat order does not recover $100 CAC if $60 goes to
            product and fulfilment costs.
          </p>
        </Reveal>
      </section>

      {/* TRACK BY COHORT */}
      <section className="relative py-10">
        <div className="absolute inset-0 -z-10 bg-black/15" />
        <div className="mx-auto max-w-3xl px-4">
          <Reveal>
            <h2 className="text-2xl md:text-3xl font-extrabold mb-4">Track by cohort</h2>
            <p className="text-white/60 leading-relaxed text-sm max-w-2xl">
              Customers acquired from different channels, offers and first
              products can have different payback periods. A campaign with a
              higher CPA may still be better if it acquires customers who
              repeat much faster. Payback bridges advertising metrics with
              financial reality.
            </p>
          </Reveal>
        </div>
      </section>

      {/* RELATED */}
      <section className="mx-auto max-w-3xl px-4 py-10">
        <Reveal>
          <h2 className="text-xl md:text-2xl font-extrabold mb-4">Related reading</h2>
          <ul className="space-y-2 text-sm">
            <li>
              <Link href="/resources/ecommerce-cac-payback-period" className="text-cyan-300 underline underline-offset-4 hover:text-cyan-200">
                How Long Can Ecommerce Brands Afford to Wait for Customer Payback?
              </Link>
            </li>
            <li>
              <Link href="/resources/calculate-repeat-customer-value-shopify" className="text-cyan-300 underline underline-offset-4 hover:text-cyan-200">
                How to Calculate Repeat Customer Value for a Shopify Store
              </Link>
            </li>
            <li>
              <Link href="/resources/lose-money-first-order-ecommerce" className="text-cyan-300 underline underline-offset-4 hover:text-cyan-200">
                When Is It Okay to Lose Money on the First Shopify Order?
              </Link>
            </li>
            <li>
              <Link href="/resources/how-much-should-ecommerce-spend-to-acquire-customer" className="text-cyan-300 underline underline-offset-4 hover:text-cyan-200">
                How Much Should Ecommerce Brands Spend to Acquire a New Customer?
              </Link>
            </li>
          </ul>
        </Reveal>
      </section>

      {/* CTA */}
      <section className="mx-auto max-w-2xl px-4 py-20 text-center">
        <Reveal>
          <h2 className="text-2xl md:text-3xl font-extrabold">Growing revenue but constantly cash constrained?</h2>
          <p className="mt-4 text-white/60 max-w-lg mx-auto">
            If your store is growing revenue but constantly feels cash
            constrained, send us an inquiry. Acquisition payback may be part
            of the explanation.
          </p>
          <ManagedServicesCTA className="mt-8 justify-center" />
        </Reveal>
      </section>
    </ProductPageShell>
  );
}
