// Single source of truth for the Resources archive AND the sitemap.
// Adding an article here makes it appear on /resources and in sitemap.xml —
// nothing else needs to be touched for a new article to be discoverable.

export type Article = { title: string; desc: string; href: string };

export const CORE_GUIDES: (Article & { category: string })[] = [
  {
    title: "Shopify Attribution Software",
    desc: "How to connect Meta and Google Ads clicks to real Shopify orders: first-click, last-click and multi-touch models explained.",
    category: "Attribution",
    href: "/shopify-attribution",
  },
  {
    title: "Shopify Server-Side Tracking",
    desc: "Why browser tracking misses a growing share of orders, how server-side tracking works, and what it still can't solve.",
    category: "Tracking",
    href: "/server-side-tracking-shopify",
  },
  {
    title: "Meta CAPI for Shopify",
    desc: "How the Conversions API works alongside the Pixel: event matching, deduplication, and Event Match Quality.",
    category: "Meta Ads",
    href: "/meta-capi-shopify",
  },
  {
    title: "Google Ads Conversion Tracking for Shopify",
    desc: "Why Google Ads and Shopify rarely agree on revenue, and how enhanced conversions and Consent Mode fit in.",
    category: "Google Ads",
    href: "/google-ads-conversion-tracking-shopify",
  },
  {
    title: "Shopify ROAS Tracking",
    desc: "Why adding Meta ROAS to Google ROAS overstates performance, and how blended ROAS and MER differ.",
    category: "Attribution",
    href: "/shopify-roas-tracking",
  },
];

export const CATEGORIES: { id: string; label: string; intro: string; items: Article[] }[] = [
  {
    id: "meta-ads",
    label: "Meta Ads",
    intro: "Diagnosing performance problems and tracking issues on Meta: Facebook and Instagram ads for Shopify stores.",
    items: [
      { title: "Meta Ads Clicks but No Sales? Diagnose It First", desc: "A funnel walkthrough for finding exactly where the drop happens before touching the campaign.", href: "/resources/meta-ads-clicks-no-sales" },
      { title: "Meta Ads ROAS Dropped Suddenly? Ads, Website or Tracking", desc: "How to tell an actual performance decline apart from a reported one.", href: "/resources/meta-ads-roas-dropped" },
      { title: "Meta Ads Shows Sales but Shopify Has No Matching Orders", desc: "The usual configuration causes behind this specific, urgent-looking mismatch.", href: "/resources/meta-ads-shows-sales-shopify-no-orders" },
      { title: "Good CTR and Low CPC but No Sales on Meta Ads: What's Wrong", desc: "Why attractive top-funnel metrics can hide low-intent traffic.", href: "/resources/good-ctr-low-cpc-no-sales-meta-ads" },
      { title: "Why Is Your Meta Ads CPM So High?", desc: "What actually moves CPM, and why it isn't the number to react to on its own.", href: "/resources/why-is-meta-ads-cpm-high" },
      { title: "Why Shopify and Meta Ads Show Different Sales Numbers", desc: "Attribution windows, view-through credit and consent limits explain most of the gap.", href: "/resources/why-shopify-meta-sales-dont-match" },
      { title: "How to Fix Duplicate Purchases in Meta Ads for Shopify", desc: "The usual causes, and a step-by-step way to diagnose which one you have.", href: "/resources/fix-duplicate-meta-purchases-shopify" },
      { title: "Meta Event Match Quality for Shopify Explained", desc: "What EMQ measures, what moves it, and why a higher score isn't the same as better attribution.", href: "/resources/meta-event-match-quality-shopify" },
      { title: "Meta Pixel vs Conversions API for Shopify", desc: "What the Pixel sees, what CAPI recovers, and how to run both without double-counting.", href: "/resources/meta-pixel-vs-capi-shopify" },
      { title: "Meta Ads Sales Drop on Weekends: Is That Normal?", desc: "How to tell a real day-of-week pattern apart from ordinary week-to-week noise.", href: "/resources/meta-ads-sales-drop-weekends" },
      { title: "Why Meta Ads Performance Changes After Increasing the Budget", desc: "Why scaling spend changes the auction, and how to judge marginal ROAS instead of the old blended number.", href: "/resources/meta-ads-performance-changes-after-budget-increase" },
      { title: "Should Ecommerce Brands Use Meta Lead Ads or Send Traffic to Shopify?", desc: "The decision comes down to buying friction and customer intent, not the cheapest-looking Meta objective.", href: "/resources/meta-lead-ads-vs-website-conversions" },
      { title: "Should You Optimize Meta Ads for Add to Cart or Purchase?", desc: "More add-to-cart volume isn't the same signal as a purchase. Here's when each optimization event actually helps.", href: "/resources/meta-ads-optimize-add-to-cart-or-purchase" },
      { title: "When Is Your Meta Ads Account Ready to Optimize for Purchases?", desc: "What determines whether the purchase event is a usable signal, instead of a waiting period to earn.", href: "/resources/when-meta-ads-account-ready-optimize-purchases" },
      { title: "Meta Ads New Customer Acquisition: How Should You Measure It?", desc: "Separating new-customer acquisition from total attributed revenue using Shopify's own customer data.", href: "/resources/meta-ads-new-customer-acquisition-measurement" },
      { title: "How Long Should You Let Meta Ads Run Before Making Changes?", desc: "Why the right waiting period depends on data volume, not a fixed number of days.", href: "/resources/how-long-should-meta-ads-run-before-changes" },
      { title: "How Much Data Does Meta Ads Need Before You Can Judge Performance?", desc: "Matching your confidence to the amount of evidence you actually have, level by level.", href: "/resources/how-much-data-does-meta-ads-need" },
      { title: "Meta Ads Learning Phase Explained: Should You Worry About It?", desc: "What learning measures, what disrupts it, and why the delivery label isn't the business outcome.", href: "/resources/meta-ads-learning-phase-explained" },
      { title: "Should You Use Advantage+ Shopping Campaigns for Shopify?", desc: "Automation can't fix a weak offer or broken tracking. The business questions that actually decide it.", href: "/resources/advantage-plus-shopping-campaigns-shopify" },
      { title: "Meta Ads Broad Targeting vs Interests: What Works Better for Ecommerce?", desc: "Why the two solve different problems, and how creative does part of the targeting work.", href: "/resources/meta-ads-broad-vs-interest-targeting" },
      { title: "Should You Retarget Website Visitors on Meta Ads?", desc: "Why retargeting ROAS often looks better than the incremental value it actually creates.", href: "/resources/should-you-retarget-website-visitors-meta-ads" },
      { title: "How Much of Your Meta Ads Budget Should Go to Retargeting?", desc: "Why the right split is set by audience size and saturation signals, not a fixed percentage.", href: "/resources/how-much-meta-ads-budget-retargeting" },
      { title: "How Often Should You Change Meta Ad Creatives?", desc: "Watching for real fatigue signals instead of refreshing on a fixed calendar.", href: "/resources/how-often-change-meta-ad-creatives" },
      { title: "How Do You Know When a Meta Ad Is Fatigued?", desc: "The signals that actually indicate fatigue, read together instead of in isolation.", href: "/resources/how-to-tell-meta-ad-fatigue" },
      { title: "Meta Ads Frequency Too High: When Does It Become a Problem?", desc: "There's no universal ceiling. Pair frequency with CTR, CPA and reach before reacting.", href: "/resources/meta-ads-frequency-too-high" },
      { title: "Should You Pause a Meta Ad That Has No Sales?", desc: "Zero sales isn't automatically a bad ad. Here's how to judge it against target CPA and funnel activity.", href: "/resources/should-you-pause-meta-ad-no-sales" },
      { title: "Should You Scale a Winning Meta Ad or Duplicate It?", desc: "Why a duplicate doesn't clone performance, and what a genuine scaling test requires.", href: "/resources/scale-winning-meta-ad-or-duplicate" },
      { title: "Meta Retargeting Is Taking Credit for Too Many Sales: What to Do", desc: "High retargeting ROAS often isn't incremental revenue. How to spot over-attribution and set a sensible budget split.", href: "/resources/meta-retargeting-taking-credit-for-sales" },
      { title: "What Makes a Good Meta Ad for Ecommerce?", desc: "Why many ecommerce ads are built backwards, and how to judge creative beyond CTR.", href: "/resources/what-makes-good-meta-ad-ecommerce" },
      { title: "UGC Ads vs Product Ads: Which Converts Better?", desc: "UGC and polished product ads communicate different kinds of proof. Here's when each format wins.", href: "/resources/ugc-ads-vs-product-ads" },
      { title: "Static Images vs Video Ads for Ecommerce", desc: "The better format depends on what needs to be communicated, not which one is trending.", href: "/resources/static-images-vs-video-ads-ecommerce" },
      { title: "Carousel Ads vs Single Image Ads: Which Should You Use?", desc: "Carousels help when sequence or variety helps the sale. Single images help when one message deserves all the attention.", href: "/resources/carousel-ads-vs-single-image-ads" },
      { title: "Why Your Meta Ads Have Good Creative Metrics but Poor Sales", desc: "Hook rate, watch time and CTR describe attention. Revenue requires attention from the right people.", href: "/resources/good-meta-ad-metrics-but-poor-sales" },
      { title: "Increasing Meta Ads Budget: Is the 20% Rule Real?", desc: "Why the 20% rule is a useful default, not a law, and what actually determines a safe increase.", href: "/resources/meta-ads-20-percent-budget-rule" },
      { title: "How Many Meta Ads Should You Test at Once?", desc: "Why the right testing volume is set by budget and conversion volume, not a round number.", href: "/resources/how-many-meta-ads-test-at-once" },
      { title: "How Many Creatives Does a Shopify Store Need for Meta Ads?", desc: "Why creative volume should scale with ad spend, not catalog size.", href: "/resources/how-many-creatives-shopify-meta-ads" },
      { title: "Meta Ads Campaign Budget vs Ad Set Budget: Which Should You Use?", desc: "CBO and ad set budgets answer different questions. Choose based on the job at hand.", href: "/resources/campaign-budget-vs-ad-set-budget-meta" },
      { title: "Meta Ads Cost Per Purchase Increasing: What to Check", desc: "How to split a rising CPA into CPC, conversion rate and tracking to find the real cause.", href: "/resources/meta-ads-cost-per-purchase-increasing" },
      { title: "Why Meta Ads Work One Week and Fail the Next", desc: "Why weekly swings are often normal variance, and how to tell that apart from a real decline.", href: "/resources/why-meta-ads-work-one-week-fail-next" },
      { title: "How to Tell Whether Your Meta Ad Creative Is the Problem", desc: "Diagnosing creative failure before replacing an ad without knowing why it isn't working.", href: "/resources/how-to-tell-meta-ad-creative-problem" },
      { title: "What Is a Good Hook for a Meta Ad?", desc: "A good hook is the first piece of information that makes the right person think this might be for me.", href: "/resources/good-hook-for-meta-ad" },
      { title: "Should Your Meta Ad Show the Price?", desc: "Showing price can reduce clicks and improve the campaign at the same time.", href: "/resources/should-meta-ads-show-price" },
      { title: "Should Ecommerce Ads Lead With the Product or the Problem?", desc: "Some products sell themselves visually. Others need the problem explained first.", href: "/resources/product-led-vs-problem-led-ads" },
      { title: "How Many Variations of a Winning Meta Ad Should You Make?", desc: "Discovering why an ad won and preserving that reason while exploring new executions.", href: "/resources/how-many-variations-winning-meta-ad" },
      { title: "Why Winning Meta Ad Creatives Stop Working", desc: "The audience, the auction, the offer or the website can all be the real reason a winner declines.", href: "/resources/why-winning-meta-creatives-stop-working" },
      { title: "Should You Reuse Old Winning Meta Ads?", desc: "Old creative is worth retesting, but it isn't guaranteed to become a winner again.", href: "/resources/should-you-reuse-old-winning-meta-ads" },
      { title: "How Long Does a Meta Ad Creative Usually Last?", desc: "Exposure determines lifespan more than calendar days.", href: "/resources/how-long-does-meta-ad-creative-last" },
      { title: "Meta Ad Creative Testing: What Should You Test First?", desc: "Test the selling idea before the execution: a hierarchy that produces real learning.", href: "/resources/meta-ad-creative-testing-what-to-test-first" },
      { title: "Does Meta Ad Engagement Actually Matter for Sales?", desc: "An ad with 10,000 likes and no profitable sales is not a successful sales ad.", href: "/resources/does-meta-ad-engagement-matter-for-sales" },
      { title: "Should Meta Ads Get Credit for Returning Customer Purchases?", desc: "Meta can legitimately claim a repeat-purchase conversion. That doesn't mean the ad caused it.", href: "/resources/should-meta-ads-get-credit-returning-customers" },
      { title: "Should Shopify Stores Run Meta Ads in Multiple Countries?", desc: "Yes, but only when the business can serve those countries competitively. Here's what to check before expanding.", href: "/resources/meta-ads-multiple-countries-shopify" },
      { title: "One Meta Campaign for Multiple Countries or Separate Campaigns?", desc: "Combining markets gives Meta more data; separating them gives you more control over budget and economics.", href: "/resources/one-meta-campaign-multiple-countries-vs-separate" },
      { title: "How to Check Whether Your Meta Pixel Is Working", desc: "Receiving a PageView doesn't mean the Pixel works. Here's how to test the full journey through to a correct Purchase event.", href: "/resources/how-to-check-meta-pixel-working-shopify" },
      { title: "How to Check Whether Meta CAPI Is Working", desc: "'Server events are appearing' isn't the same as accurate, deduplicated business events.", href: "/resources/how-to-check-meta-capi-working" },
      { title: "Why Purchase Event IDs Matter for Meta CAPI", desc: "The event ID is how Meta recognizes a browser and server Purchase as one business event instead of two.", href: "/resources/meta-capi-event-id-deduplication" },
      { title: "Meta Pixel Helper Shows Multiple Pixels: Is That a Problem?", desc: "Multiple Pixels on a site aren't automatically wrong. The problem is when nobody knows why they're there.", href: "/resources/meta-pixel-helper-multiple-pixels" },
      { title: "Should Retargeting Campaigns Include Existing Customers?", desc: "Sometimes: the answer depends on what the campaign is selling, not a blanket always-exclude-purchasers rule.", href: "/resources/should-retargeting-include-existing-customers" },
    ],
  },
  {
    id: "google-ads",
    label: "Google Ads",
    intro: "Search, Shopping and Performance Max performance and conversion tracking problems for Shopify stores.",
    items: [
      { title: "Google Ads Clicks But No Sales? What to Check First", desc: "Separating a real sales problem from a tracking one before touching the campaign.", href: "/resources/google-ads-clicks-no-sales" },
      { title: "Google Ads Not Tracking Shopify Purchases? Step-by-Step Diagnosis", desc: "A technical checklist covering conversion actions, tags, GA4 import and Enhanced Conversions.", href: "/resources/google-ads-not-tracking-shopify-purchases" },
      { title: "Duplicate Google Ads Conversions on Shopify", desc: "Why Google can look like it's reporting more sales than you actually have.", href: "/resources/google-ads-duplicate-conversions-shopify" },
      { title: "Google Ads Conversion Value Is Wrong on Shopify", desc: "How subtotal, tax, shipping and discounts can all change what value gets reported.", href: "/resources/google-ads-conversion-value-wrong-shopify" },
      { title: "Google Ads and GA4 Don't Match: Which Numbers Should You Trust?", desc: "Why the two systems are built to answer different questions.", href: "/resources/google-ads-ga4-dont-match" },
      { title: "Google Ads Conversions Suddenly Dropped: Performance or Tracking?", desc: "A set of scenarios for reading conversions against Shopify's own numbers.", href: "/resources/google-ads-conversions-dropped-suddenly" },
      { title: "Google Ads Says I Have Conversions but Shopify Has No Orders", desc: "Almost always a labeling or configuration issue, not a phantom sale.", href: "/resources/google-ads-conversions-no-shopify-orders" },
      { title: "Google Ads Clicks Don't Match Shopify Sessions: Why?", desc: "Why a click and a session are never going to be the same number.", href: "/resources/google-ads-clicks-vs-shopify-sessions" },
      { title: "Should You Import GA4 Purchases Into Google Ads on Shopify?", desc: "Native conversion tracking vs GA4 import, and why running both as primary causes trouble.", href: "/resources/import-ga4-conversions-google-ads-shopify" },
      { title: "Why Google Ads and Shopify Revenue Don't Match", desc: "Conversion date vs. order date, duplicate conversion actions, refunds, and cross-channel overlap.", href: "/resources/google-ads-shopify-revenue-doesnt-match" },
      { title: "Enhanced Conversions for Shopify Explained", desc: "What Enhanced Conversions recover, what they don't fix, and how they relate to server-side tracking.", href: "/resources/enhanced-conversions-shopify" },
      { title: "Performance Max Spending Money but Getting No Sales", desc: "Why checking tracking comes before touching the feed, bidding or budget.", href: "/resources/performance-max-no-sales" },
      { title: "Performance Max ROAS Suddenly Dropped: How to Diagnose It", desc: "Tracking, feed changes, seasonality and brand-vs-non-brand mix, in order.", href: "/resources/performance-max-roas-dropped" },
      { title: "Google Shopping Getting Clicks but No Sales", desc: "Why query relevance, feed quality and price shown in the ad matter more here than in Search.", href: "/resources/google-shopping-clicks-no-sales" },
      { title: "Google Merchant Center Products Disapproved: What It Means for Sales", desc: "Disapproved products don't show at all, and a shrinking catalog can look like a campaign problem.", href: "/resources/google-merchant-center-product-disapproved" },
      { title: "Google Ads Search Terms: What Should Ecommerce Advertisers Look For?", desc: "Keywords are what you targeted. Search terms are what you actually paid for.", href: "/resources/google-ads-search-terms-ecommerce" },
      { title: "Broad Match vs Phrase Match vs Exact Match for Ecommerce", desc: "Modern match types use context and intent, not just literal string matching.", href: "/resources/broad-vs-phrase-vs-exact-match-ecommerce" },
      { title: "Should Shopify Stores Bid on Their Own Brand Name?", desc: "Branded search can protect your result and control messaging, but is it incremental?", href: "/resources/should-you-bid-on-your-brand-name-google-ads" },
      { title: "Are Competitor Keywords Worth Bidding on in Google Ads?", desc: "The intent behind a competitor-name search isn't neutral, and that has a cost.", href: "/resources/competitor-keywords-google-ads-worth-it" },
      { title: "Is Your Google Ads Brand Campaign Taking Credit for Organic Sales?", desc: "A branded campaign can report enormous ROAS while creating little incremental revenue.", href: "/resources/google-brand-campaign-taking-credit-organic-sales" },
      { title: "How Much Budget Should Go to Brand vs Non-Brand Google Ads?", desc: "Brand demand is constrained by how many people already search for you. Let marginal opportunity set the split.", href: "/resources/google-ads-brand-vs-non-brand-budget" },
      { title: "Why Google Search Ads Get Clicks but Low-Quality Traffic", desc: "Poor traffic usually comes from a mismatch between keyword, search term and landing page.", href: "/resources/google-ads-low-quality-traffic" },
      { title: "What Is a Good Google Ads Conversion Rate for Ecommerce?", desc: "CPA = CPC ÷ conversion rate. The right benchmark is your own margins, not an industry average.", href: "/resources/good-google-ads-conversion-rate-ecommerce" },
      { title: "What Is a Good Google Ads CTR for Ecommerce?", desc: "CTR measures relevance, not revenue. Profit beats the click-through screenshot.", href: "/resources/good-google-ads-ctr-ecommerce" },
      { title: "Why Your Google Ads CPC Suddenly Increased", desc: "An auction symptom with several possible causes, and higher CPC isn't automatically bad.", href: "/resources/google-ads-cpc-suddenly-increased" },
      { title: "Google Ads by Country: Should You Separate Campaigns?", desc: "Separate when markets need different budgets, targets, feeds or language. Combine when they genuinely behave alike.", href: "/resources/separate-google-ads-campaigns-by-country" },
      { title: "How to Check Whether Google Ads Conversion Tracking Is Working", desc: "An 'active' conversion action can still record the wrong thing. Here's how to test the entire purchase event.", href: "/resources/check-google-ads-conversion-tracking-working-shopify" },
      { title: "What Is a Transaction ID and Why Does Google Ads Need It?", desc: "A small implementation detail with a large impact on whether Google counts a purchase once or twice.", href: "/resources/google-ads-transaction-id-ecommerce" },
      { title: "Google Ads Search Impression Share Explained for Ecommerce", desc: "Search impression share estimates how often your ads appeared compared with the number of times Google believed they were eligible to appear.", href: "/resources/google-ads-search-impression-share-explained" },
      { title: "Lost Impression Share Due to Budget: Should You Increase Spend?", desc: "\"Limited by budget\" can feel like Google is telling you to spend more.", href: "/resources/lost-impression-share-budget-increase" },
      { title: "Lost Impression Share Due to Rank: What Should You Fix?", desc: "When Google reports lost impression share due to rank, your campaign was eligible for searches but did not have enough Ad Rank to win all of the impressions.", href: "/resources/lost-impression-share-rank-google-ads" },
      { title: "Should Ecommerce Stores Use Broad Match With Smart Bidding?", desc: "Broad match with automated bidding can discover valuable searches you would never build manually.", href: "/resources/broad-match-smart-bidding-ecommerce" },
      { title: "How Many Keywords Should a Google Ads Campaign Have?", desc: "The correct number of keywords is the number needed to cover meaningful search intent without creating a structure you cannot manage.", href: "/resources/how-many-keywords-google-ads-campaign" },
      { title: "Google Ads Negative Keywords for Ecommerce: What to Look For", desc: "Negative keywords stop Google from showing ads for searches you deliberately do not want.", href: "/resources/negative-keywords-ecommerce-google-ads" },
      { title: "Why Google Ads Spend Increases Without More Sales", desc: "More Google spend does not automatically create proportionally more demand.", href: "/resources/google-ads-spend-increases-no-more-sales" },
      { title: "Google Ads Search Campaign vs Performance Max for Ecommerce", desc: "Search campaigns and Performance Max solve different parts of Google advertising.", href: "/resources/search-campaign-vs-performance-max-ecommerce" },
      { title: "Should You Run Search Ads if Performance Max Is Already Running?", desc: "Yes, Search can still have a clear role even when Performance Max is active.", href: "/resources/run-search-ads-with-performance-max" },
      { title: "Google Ads Exact Match Isn't Really Exact: What Ecommerce Advertisers Should Know", desc: "An exact-match keyword no longer means your ad can appear only when someone types precisely the same characters.", href: "/resources/google-ads-exact-match-not-exact" },
      { title: "Should You Separate Brand Traffic From Performance Max?", desc: "Brand traffic can make Performance Max look more efficient than its true acquisition impact.", href: "/resources/separate-brand-traffic-performance-max" },
      { title: "How Much of Performance Max Revenue Comes From Brand Searches?", desc: "There is no universal percentage.", href: "/resources/performance-max-brand-revenue" },
      { title: "How to Tell What Performance Max Is Actually Doing", desc: "Performance Max is deliberately more automated than traditional Search, which means advertisers often feel they are funding a black box.", href: "/resources/how-to-see-what-performance-max-is-doing" },
      { title: "Performance Max vs Standard Shopping: Which Is Better?", desc: "Performance Max offers more automation and access to broader Google inventory.", href: "/resources/performance-max-vs-standard-shopping" },
      { title: "Should You Put All Products in One Performance Max Campaign?", desc: "Putting every product into one PMax campaign is simple.", href: "/resources/all-products-one-performance-max-campaign" },
      { title: "When Should You Split Products Into Multiple PMax Campaigns?", desc: "Split PMax campaigns when separate control creates a business advantage.", href: "/resources/when-to-split-performance-max-campaigns" },
      { title: "Best Sellers vs Low Sellers: How Should You Structure Google Shopping?", desc: "Best sellers deserve attention because they have proven demand.", href: "/resources/best-sellers-vs-low-sellers-google-shopping-structure" },
      { title: "Should You Exclude Poor-Performing Products From Performance Max?", desc: "Sometimes, but \"no sales\" alone isn't enough evidence to decide.", href: "/resources/exclude-poor-performing-products-performance-max" },
      { title: "Product Feed Titles: How Much Do They Matter for Google Shopping?", desc: "Product titles are one of the clearest signals Google has for understanding what you sell.", href: "/resources/google-shopping-product-feed-titles" },
      { title: "Google Shopping Feed Optimization: What Actually Matters?", desc: "Feed optimization is often sold as a bag of hacks.", href: "/resources/google-shopping-feed-optimization" },
      { title: "Why Some Shopify Products Never Get Google Shopping Impressions", desc: "A product can be approved in Merchant Center and still receive almost no Shopping impressions.", href: "/resources/google-shopping-products-no-impressions" },
      { title: "Google Shopping Has High ROAS but Low Volume: Should You Scale?", desc: "A high ROAS at low spend is encouraging, but it does not prove the same efficiency exists at higher volume.", href: "/resources/google-shopping-high-roas-low-volume" },
      { title: "Performance Max Spending Mostly on One Product: Is That a Problem?", desc: "Not necessarily. Google may simply have found one product is the easiest way to generate conversion value.", href: "/resources/performance-max-spending-mostly-one-product" },
      { title: "Why Performance Max Stops Spending", desc: "When Performance Max suddenly spends less, do not start by increasing the budget.", href: "/resources/why-performance-max-stops-spending" },
      { title: "Performance Max Is Overspending on Branded Searches: What to Do", desc: "If PMax reports spectacular results because it captures people already searching your brand, the campaign can look more incremental than it really is.", href: "/resources/performance-max-brand-search-overspending" },
      { title: "How Long Should a New Performance Max Campaign Run Before You Judge It?", desc: "A new PMax campaign needs enough time and conversions to show a pattern, but there is no responsible answer such as \"always wait six weeks.\"", href: "/resources/how-long-run-performance-max-before-judging" },
      { title: "Performance Max Learning Period: What Should You Avoid Changing?", desc: "The fastest way to make a new automated campaign impossible to understand is to change several important inputs every few days.", href: "/resources/performance-max-learning-period-avoid-changing" },
      { title: "Performance Max vs Meta Ads for New Product Launches", desc: "A new product with no search demand behaves very differently from a new product in an established category.", href: "/resources/performance-max-vs-meta-ads-new-product-launch" },
      { title: "Why Google Shopping Shows the Wrong Price", desc: "When a Shopping ad shows a different price from Shopify, treat it as both a conversion problem and a feed-quality problem.", href: "/resources/google-shopping-wrong-price" },
      { title: "Merchant Center Feed Issues That Quietly Hurt Performance", desc: "Not every Merchant Center problem produces a dramatic red \"account suspended\" warning.", href: "/resources/merchant-center-feed-issues-hurt-performance" },
    ],
  },
  {
    id: "shopify-growth",
    label: "Shopify Growth",
    intro: "Reading the funnel (sessions, product views, cart, checkout and purchase) to find where conversion actually breaks.",
    items: [
      { title: "Shopify Traffic but No Sales? Find Where the Funnel Is Breaking", desc: "A full-funnel diagnostic instead of a generic CRO checklist.", href: "/resources/shopify-traffic-no-sales" },
      { title: "Shopify Conversion Rate Suddenly Dropped: What to Check First", desc: "How to find the exact day something changed, and cross-reference against it.", href: "/resources/shopify-conversion-rate-dropped" },
      { title: "Lots of Add to Carts but No Purchases on Shopify", desc: "Shipping shock, payment options and general trust: what usually sits between the two.", href: "/resources/shopify-add-to-cart-no-purchases" },
      { title: "Shopify Customers Reach Checkout but Don't Buy: What to Check", desc: "The narrower, later-stage causes specific to the checkout step itself.", href: "/resources/shopify-checkout-no-purchase" },
      { title: "Shopify Sales Dropped but Traffic Is the Same: What Does That Tell You?", desc: "Why stable sessions point the problem at the store, not media reach.", href: "/resources/shopify-sales-down-traffic-same" },
      { title: "Shopify Revenue Is Up but Meta and Google ROAS Are Down", desc: "Why total growth and platform ROAS can move in opposite directions.", href: "/resources/shopify-revenue-up-roas-down" },
      { title: "Why Your Ads Perform Well in One Country and Poorly in Another", desc: "Auction cost, shipping, payment and creative context usually explain more than an inconsistent algorithm.", href: "/resources/ads-perform-differently-by-country-ecommerce" },
      { title: "International Shipping Is Killing Your Conversion Rate: How to Diagnose It", desc: "If the funnel collapses at checkout, shipping cost, delivery time and duties are the first areas to inspect.", href: "/resources/international-shipping-low-conversion-ecommerce" },
      { title: "Why International Traffic Has a Lower Shopify Conversion Rate", desc: "Shipping, currency, duties, payment, trust, language and product fit all add uncertainty to the cross-border journey.", href: "/resources/international-traffic-lower-conversion-ecommerce" },
      { title: "Should You Run Different Meta Creatives for Different Countries?", desc: "If customer motivations, language or offers differ, country-specific creatives can improve performance.", href: "/resources/should-you-run-different-meta-creatives-for-different" },
      { title: "How to Choose Which Country to Expand Ecommerce Ads Into Next", desc: "Do not choose the next country because Meta CPM is cheap.", href: "/resources/how-to-choose-which-country-to-expand-ecommerce-ads" },
      { title: "When Is a Shopify Store Ready to Advertise Internationally?", desc: "A store is ready for international ads when the business can deliver an experience that is competitive enough for the target market.", href: "/resources/shopify-ready-for-international-ads" },
    ],
  },
  {
    id: "cro-landing-pages",
    label: "CRO & Landing Pages",
    intro: "Product pages, checkout friction, offers and the mobile buying path, turning existing traffic into more Shopify orders.",
    items: [
      { title: "Should You Use Sticky Add-to-Cart Buttons on Shopify?", desc: "Sticky purchase controls can help long mobile product pages, or become another intrusive bar fighting for screen space.", href: "/resources/sticky-add-to-cart-shopify-conversion" },
      { title: "Product Reviews vs Testimonials: Which Build More Trust?", desc: "Reviews reduce risk on a specific product. Testimonials explain a broader outcome. The question is what uncertainty needs removing.", href: "/resources/product-reviews-vs-testimonials-ecommerce" },
      { title: "How Many Product Images Should a Shopify Product Page Have?", desc: "The right gallery is the smallest set of images that answers the customer's visual questions. The goal is confidence, not count.", href: "/resources/how-many-product-images-shopify" },
      { title: "Should Shopify Stores Show Delivery Dates Before Checkout?", desc: "Delivery timing is part of the product decision, not a detail customers should discover at the final checkout step.", href: "/resources/show-delivery-date-product-page-shopify" },
      { title: "Collection Page vs Product Page for Google Shopping Traffic", desc: "A Shopping click sets a specific expectation. The destination should almost always confirm it before offering ways to browse.", href: "/resources/collection-page-vs-product-page-google-shopping" },
      { title: "Why Unexpected Shipping Costs Kill Ecommerce Sales", desc: "A shopper can accept a $79 product and still abandon when checkout suddenly becomes $94.", href: "/resources/unexpected-shipping-costs-cart-abandonment" },
      { title: "Should You Create Different Landing Pages for Meta and Google Ads?", desc: "Google often captures an existing need while Meta creates the interest. That difference should shape the landing page.", href: "/resources/different-landing-pages-meta-and-google-ads" },
      { title: "Should Shopify Stores Offer Buy Now, Pay Later?", desc: "BNPL can help conversion on higher-AOV products, but it introduces fees and a different way of presenting price.", href: "/resources/buy-now-pay-later-shopify-conversion" },
      { title: "Why Sending All Paid Traffic to Your Homepage Is Usually a Mistake", desc: "A homepage serves many jobs. A paid campaign usually has one, and every extra decision costs attention.", href: "/resources/paid-ads-traffic-to-homepage-ecommerce" },
      { title: "Does Klarna Increase Ecommerce Conversion Rate?", desc: "Klarna can remove a real payment barrier for some stores, but it is not a universal conversion law.", href: "/resources/does-klarna-increase-conversion-rate" },
      { title: "Shopify Cart Drawer vs Cart Page: Which Converts Better?", desc: "Either can convert well when it helps the customer understand the order and move toward checkout.", href: "/resources/cart-drawer-vs-cart-page-shopify" },
      { title: "How Import Duties Affect International Shopify Conversion Rates", desc: "Duties hurt conversion most when customers discover them after they thought they knew the final price.", href: "/resources/import-duties-ecommerce-conversion-rate" },
      { title: "Should You Show Duties and Taxes Before Checkout?", desc: "Yes, as early and accurately as practical. Customers do not enjoy discovering mandatory costs after deciding to buy.", href: "/resources/show-duties-taxes-before-checkout-ecommerce" },
      { title: "Should You Translate Shopify Landing Pages for Paid Ads?", desc: "If you run ads in a customer's local language, the landing page should normally continue in that language.", href: "/resources/translate-landing-pages-for-international-ads" },
      { title: "Ad-to-Landing-Page Message Match: Why It Matters for Conversion Rate", desc: "Paid traffic creates an expectation the landing page must confirm. Here's how a broken chain of claim, headline, offer and proof quietly kills strong ads.", href: "/resources/ad-to-landing-page-message-match" },
      { title: "Is Your Shopify Discount Code Box Hurting Conversion Rate?", desc: "A visible discount field can tell a full-price customer they're paying more than someone else.", href: "/resources/discount-code-box-checkout-conversion" },
      { title: "Does Social Proof Actually Increase Ecommerce Conversion Rate?", desc: "Social proof reduces uncertainty when it's specific and well placed, and can backfire when it feels manufactured.", href: "/resources/social-proof-ecommerce-conversion-rate" },
      { title: "Why Shopify Customers Abandon Checkout After Seeing Shipping Costs", desc: "When abandonment jumps after shipping appears, the customer has learned something about the deal they didn't know earlier.", href: "/resources/shopify-checkout-abandonment-shipping-costs" },
      { title: "Where Should Customer Reviews Appear on a Shopify Product Page?", desc: "Reviews are a trust resource that supports several stages of the decision, not one block at the bottom of the page.", href: "/resources/where-to-put-reviews-shopify-product-page" },
      { title: "Should Shopify Stores Use Popups?", desc: "Popups can turn anonymous traffic into an audience you can contact again, or interrupt the exact customer you paid to bring to the store.", href: "/resources/should-shopify-stores-use-popups" },
      { title: "Star Ratings vs Written Reviews: Which Matter More?", desc: "Ratings help customers scan and written reviews help them understand. The two answer different trust questions.", href: "/resources/star-ratings-vs-written-reviews-ecommerce" },
      { title: "Do Countdown Timers Actually Improve Ecommerce Conversion Rates?", desc: "Real deadlines create urgency. Timers that reset on every refresh teach visitors the deadline is meaningless.", href: "/resources/countdown-timer-ecommerce-conversion-rate" },
      { title: "Should Shopify Stores Show the Number of Products Sold?", desc: "A genuine purchase count can reassure shoppers, but a fabricated or inflated one makes the store look less credible.", href: "/resources/show-number-sold-product-page-ecommerce" },
      { title: "Does \"Only X Left\" Increase Conversion or Hurt Trust?", desc: "Real scarcity helps a customer decide. A stock message that never changes teaches the whole store looks dishonest.", href: "/resources/only-x-left-ecommerce-conversion" },
      { title: "Is Scarcity Marketing Hurting Your Ecommerce Brand?", desc: "Genuine scarcity helps customers decide. Permanent scarcity teaches them there was never really a deadline.", href: "/resources/scarcity-marketing-ecommerce" },
      { title: "What Is a Good Shopify Conversion Rate?", desc: "A good Shopify conversion rate is one that supports profitable customer acquisition for your product, traffic mix and margins.", href: "/resources/good-shopify-conversion-rate" },
      { title: "How to Improve Shopify Conversion Rate Without Increasing Ad Spend", desc: "If traffic stays the same and conversion rate improves, revenue can grow without buying another click.", href: "/resources/improve-shopify-conversion-rate" },
      { title: "Shopify Product Page Not Converting: What to Check", desc: "A product page can fail even when the ad is doing its job.", href: "/resources/shopify-product-page-not-converting" },
      { title: "What Should Be Above the Fold on a Shopify Product Page?", desc: "The first screen of a product page should help a customer answer one question: \"Is this worth looking at?\" It does not need to contain every sales argument on the page.", href: "/resources/shopify-product-page-above-the-fold" },
      { title: "Should Shopify Product Pages Show Reviews Near the Top?", desc: "For many products, showing a review summary near the top is useful because it answers an immediate trust question: \"Have other people bought this, and were they happy?\" That does not mean the full review feed belongs above the Add to Cart button.", href: "/resources/reviews-near-top-product-page" },
      { title: "Does Free Shipping Increase Shopify Conversion Rate?", desc: "Free shipping can increase conversion because it removes one of ecommerce's most disliked surprises.", href: "/resources/does-free-shipping-increase-conversion-rate" },
      { title: "Free Shipping vs Discount: Which Converts Better?", desc: "A discount reduces the price of the product.", href: "/resources/free-shipping-vs-discount-conversion" },
      { title: "How Much Does Page Speed Affect Shopify Sales?", desc: "Page speed matters because every extra wait gives a visitor another chance to leave, especially on mobile and paid traffic.", href: "/resources/shopify-page-speed-conversion-rate" },
      { title: "Shopify Mobile Conversion Rate Lower Than Desktop: Is That Normal?", desc: "It is common for mobile and desktop conversion rates to differ, but \"mobile is always lower\" is not a useful excuse for a poor mobile store.", href: "/resources/shopify-mobile-conversion-rate-lower-than-desktop" },
      { title: "Why Shopify Mobile Traffic Doesn't Convert", desc: "When mobile traffic does not convert, start by separating traffic quality from mobile experience.", href: "/resources/shopify-mobile-traffic-not-converting" },
      { title: "Should Meta Ads Send Traffic to a Product Page or Landing Page?", desc: "Send Meta traffic to the page that continues the selling argument with the least friction.", href: "/resources/should-meta-ads-send-traffic-to-a-product-page-or" },
      { title: "Landing Page vs Product Page for Ecommerce Ads", desc: "A product page is built to sell the product in the context of the store.", href: "/resources/landing-page-vs-product-page-for-ecommerce-ads" },
      { title: "When Does an Ecommerce Brand Need a Dedicated Landing Page?", desc: "Build a dedicated landing page when the existing website cannot continue the campaign's message clearly enough.", href: "/resources/when-does-an-ecommerce-brand-need-a-dedicated-landing" },
      { title: "Why Your Landing Page Gets Clicks but No Sales", desc: "If customers clicked the ad, the ad created enough interest to earn a visit.", href: "/resources/why-your-landing-page-gets-clicks-but-no-sales" },
      { title: "What Is a Good Landing Page Conversion Rate for Ecommerce?", desc: "A good landing-page conversion rate is one that supports profitable acquisition at the cost and quality of the traffic being sent to it.", href: "/resources/what-is-a-good-landing-page-conversion-rate-for" },
      { title: "How Long Should an Ecommerce Landing Page Be?", desc: "A landing page should be long enough to answer the questions preventing the purchase and no longer.", href: "/resources/how-long-should-an-ecommerce-landing-page-be" },
      { title: "Should Your Landing Page Show the Price Above the Fold?", desc: "For normal ecommerce products, hiding the price usually adds unnecessary friction.", href: "/resources/should-your-landing-page-show-the-price-above-the-fold" },
      { title: "Should Ecommerce Landing Pages Have Navigation?", desc: "Removing navigation can keep users focused on the offer.", href: "/resources/should-ecommerce-landing-pages-have-navigation" },
      { title: "What Should the First Screen of an Ecommerce Landing Page Say?", desc: "The first screen should confirm the visitor came to the right place and give them a reason to keep going.", href: "/resources/what-should-the-first-screen-of-an-ecommerce-landing" },
      { title: "How Many CTAs Should an Ecommerce Landing Page Have?", desc: "A landing page can have several CTA buttons without having several competing goals.", href: "/resources/how-many-ctas-should-an-ecommerce-landing-page-have" },
      { title: "Product Page vs Advertorial: Which Works Better for Meta Ads?", desc: "A product page assumes the customer is ready to evaluate the product.", href: "/resources/product-page-vs-advertorial-which-works-better-for" },
      { title: "What Is an Advertorial Landing Page and When Should Ecommerce Brands Use One?", desc: "An advertorial is a sales-oriented educational page written in an article-like format.", href: "/resources/what-is-an-advertorial-landing-page-and-when-should" },
      { title: "Quiz Funnel vs Product Page: Which Converts Better?", desc: "A quiz can improve conversion when the customer genuinely needs help choosing.", href: "/resources/quiz-funnel-vs-product-page-which-converts-better" },
      { title: "Does Showing Savings in Dollars Convert Better Than Percentages?", desc: "Sometimes the dollar saving feels larger.", href: "/resources/does-showing-savings-in-dollars-convert-better-than" },
      { title: "Your Ads Get Clicks but Your Offer Doesn't Convert: How to Tell", desc: "When ads get qualified clicks and the website works technically, the problem may be the offer itself.", href: "/resources/your-ads-get-clicks-but-your-offer-doesn-t-convert-how" },
      { title: "How to Know Whether Your Ecommerce Offer Is the Problem", desc: "An offer problem often appears when customers understand the product, show interest and stop before committing money.", href: "/resources/how-to-know-whether-your-ecommerce-offer-is-the-problem" },
      { title: "Should Shopify App Costs Count as Marketing Costs?", desc: "Some Shopify apps directly support customer acquisition; others support operations, support or merchandising.", href: "/resources/should-shopify-app-costs-count-as-marketing-costs" },
      { title: "How to Find the Real Reason Customers Buy Your Product", desc: "The reason a company thinks customers buy is not always the reason customers give.", href: "/resources/how-to-find-the-real-reason-customers-buy-your-product" },
      { title: "Should Google Ads Send Traffic to a Product Page or Collection Page?", desc: "The search query should usually decide.", href: "/resources/should-google-ads-send-traffic-to-a-product-page-or" },
    ],
  },
  {
    id: "attribution",
    label: "Attribution & Analytics",
    intro: "How attribution models, ROAS and MER actually work, and why platforms rarely agree with each other or with Shopify.",
    items: [
      { title: "Why Meta and Google Both Claim the Same Shopify Sale", desc: "A worked example of why adding platform-reported revenue together overstates real sales.", href: "/resources/ad-platforms-report-more-revenue-than-shopify" },
      { title: "Why Changing Your Meta Attribution Window Changes Your ROAS", desc: "The same campaign, two different reported ROAS figures, and why.", href: "/resources/meta-attribution-window-roas" },
      { title: "View-Through Conversions: Should You Count Them?", desc: "The case for and against, and a framework instead of a flat answer.", href: "/resources/view-through-conversions-explained" },
      { title: "Shopify Attribution Models Explained", desc: "First-click, last-click, linear, position-based and data-driven: what each one rewards and hides.", href: "/resources/shopify-attribution-models" },
      { title: "How to Calculate True ROAS on Shopify", desc: "Platform ROAS vs. blended ROAS vs. true ROAS, and what actually separates them.", href: "/resources/true-roas-shopify" },
      { title: "MER vs ROAS for Shopify", desc: "ROAS depends on attribution; MER doesn't. When each one is the right tool.", href: "/resources/mer-vs-roas-shopify" },
      { title: "Does Google Ads Over-Attribute Branded Searches?", desc: "A branded click can be validly attributed and still not be incremental. The two questions need separate answers.", href: "/resources/google-ads-branded-search-over-attribution" },
      { title: "What Is Incrementality in Ecommerce Advertising?", desc: "Attribution asks which interaction gets credit. Incrementality tries to estimate causation.", href: "/resources/incrementality-ecommerce-advertising" },
      { title: "Attribution vs Incrementality: What's the Difference?", desc: "Why the same campaign can show high attributed ROAS and low incremental lift at the same time.", href: "/resources/attribution-vs-incrementality" },
      { title: "How to Calculate Your Maximum Profitable CPA", desc: "The acquisition cost at which the order still meets your profit requirement, built from contribution rather than a target that just looks good.", href: "/resources/maximum-profitable-cpa-ecommerce" },
      { title: "How to Calculate Your Maximum Profitable CPC for Google Ads", desc: "Maximum CPC = allowable CPA × conversion rate. One account-wide ceiling rarely fits brand, non-brand and Shopping.", href: "/resources/maximum-profitable-cpc-ecommerce" },
      { title: "How Gross Margin Changes Your Break-Even ROAS", desc: "Break-even ROAS = 1 ÷ gross margin, and the real number is usually higher once fees, fulfilment and returns are included.", href: "/resources/gross-margin-break-even-roas" },
      { title: "Contribution Margin vs Gross Margin for Ecommerce Advertising", desc: "Contribution margin subtracts the variable costs gross margin ignores, which is why it's the more useful number for allowable CPA.", href: "/resources/contribution-margin-vs-gross-margin-ecommerce" },
      { title: "How Currency Differences Affect Ecommerce ROAS", desc: "Why ad spend, Shopify revenue and product costs need one consistent reporting currency before ROAS means anything.", href: "/resources/currency-affects-ecommerce-roas" },
      { title: "Local Currency vs Store Currency: What Should You Use in Ads?", desc: "Customers prefer familiar local pricing. The important part is keeping the customer-facing price and tracking values consistent.", href: "/resources/local-currency-vs-store-currency-ecommerce-ads" },
      { title: "Meta Ads vs Klaviyo Attribution: Who Gets Credit for the Sale?", desc: "Meta and Klaviyo can both legitimately claim the same Shopify sale. Summing their attributed revenue overstates marketing's real impact.", href: "/resources/meta-ads-vs-klaviyo-attribution" },
      { title: "Google Ads vs Klaviyo Revenue: Why Both Can Claim the Same Customer", desc: "A customer can click a Klaviyo email, then search the brand on Google and buy. That's why both platforms can attribute the same order.", href: "/resources/google-ads-vs-klaviyo-revenue-attribution" },
      { title: "Why Returning Customers Convert Better Than New Visitors", desc: "Returning customers already solved several problems that slow a first purchase, which can distort channel ROAS.", href: "/resources/returning-customers-convert-better-ecommerce" },
      { title: "Why Shopify, GA4, Meta and Google All Show Different Revenue", desc: "Four systems can show four different revenue numbers without all four being broken. They measure different things.", href: "/resources/shopify-ga4-meta-google-revenue-different" },
      { title: "Why a 400% ROAS Can Still Lose Money", desc: "A 400% ROAS says nothing about what the product costs to make and deliver: a worked example of thin margin eating the contribution.", href: "/resources/400-roas-profitable" },
      { title: "Can You Add Meta and Google ROAS Together?", desc: "No: adding ROAS percentages together doesn't produce a meaningful total, and it can double-count the same orders.", href: "/resources/can-you-add-meta-and-google-roas-together" },
      { title: "Why Platform ROAS Can Look Great While Your Business Loses Money", desc: "ROAS compares attributed revenue with ad spend.", href: "/resources/why-platform-roas-can-look-great-while-your-business" },
      { title: "How to Calculate Break-Even ROAS for Ecommerce", desc: "Break-even ROAS tells you the revenue-to-ad-spend ratio at which the order has no contribution left after the costs you choose to include.", href: "/resources/how-to-calculate-break-even-roas-for-ecommerce" },
      { title: "Break-Even CPA Explained for Shopify Stores", desc: "Break-even CPA is the maximum acquisition cost an order can absorb before the contribution profit you are measuring reaches zero.", href: "/resources/break-even-cpa-explained-for-shopify-stores" },
      { title: "What Is a Good CPA for Ecommerce?", desc: "A good CPA is not an industry number.", href: "/resources/what-is-a-good-cpa-for-ecommerce" },
      { title: "ROAS vs Profit: Why High ROAS Doesn't Always Mean More Profit", desc: "ROAS measures revenue returned for each unit of ad spend.", href: "/resources/roas-vs-profit-why-high-roas-doesn-t-always-mean-more" },
      { title: "Why Revenue Is a Bad Metric Without Gross Margin", desc: "Revenue tells you how much customers paid.", href: "/resources/why-revenue-is-a-bad-metric-without-gross-margin" },
      { title: "New Customer ROAS vs Total ROAS: Which Matters More?", desc: "Total ROAS tells you how efficiently ad spend is associated with all reported revenue.", href: "/resources/new-customer-roas-vs-total-roas-which-matters-more" },
      { title: "Customer Acquisition Cost vs CPA: What's the Difference?", desc: "CPA and CAC are often used interchangeably, but they can describe different scopes.", href: "/resources/customer-acquisition-cost-vs-cpa-what-s-the-difference" },
      { title: "How to Calculate CAC for a Shopify Store", desc: "A practical CAC calculation answers: how much did we spend to acquire each new customer?", href: "/resources/how-to-calculate-cac-for-a-shopify-store" },
      { title: "LTV vs CAC for Ecommerce: What Should You Aim For?", desc: "LTV:CAC compares the value a customer generates over time with the cost to acquire that customer.", href: "/resources/ltv-vs-cac-for-ecommerce-what-should-you-aim-for" },
      { title: "Why Last-Click Attribution Undervalues Meta Ads", desc: "Meta often introduces customers before they are ready to buy.", href: "/resources/why-last-click-attribution-undervalues-meta-ads" },
      { title: "Why Meta View-Through Attribution Can Overvalue Meta Ads", desc: "View-through attribution gives Meta credit when a person sees an ad, does not click it and later purchases within the relevant window.", href: "/resources/why-meta-view-through-attribution-can-overvalue-meta" },
      { title: "Can Cookie Consent Reduce Your Reported ROAS?", desc: "Yes: declined consent can make ad platforms undercount conversions, making campaigns look less efficient than they really are.", href: "/resources/can-cookie-consent-reduce-your-reported-roas" },
      { title: "When Should You Exclude Existing Customers From Meta Ads?", desc: "Exclude existing customers when you need a campaign to answer a new-customer acquisition question or when the advertised product is irrelevant after purchase.", href: "/resources/when-should-you-exclude-existing-customers-from-meta" },
      { title: "Does Lowering Your Product Price Improve ROAS?", desc: "Lowering price can improve conversion and ROAS while reducing profit.", href: "/resources/does-lowering-your-product-price-improve-roas" },
      { title: "What ROAS Do You Need With a 30% Gross Margin?", desc: "At a true 30% margin, simple break-even ROAS is roughly 3.3x, before fees, returns and other costs are even counted.", href: "/resources/what-roas-do-you-need-with-a-30-percent-gross-margin" },
      { title: "What ROAS Do You Need With a 50% Gross Margin?", desc: "At a true 50% margin, simple break-even ROAS is roughly 2.0x: a lower bar, but still before other real costs are counted.", href: "/resources/what-roas-do-you-need-with-a-50-percent-gross-margin" },
      { title: "How Discounts Change Your Break-Even ROAS", desc: "Discounting reduces revenue while product and fulfilment costs often stay largely the same.", href: "/resources/how-discounts-change-your-break-even-roas" },
      { title: "How Refunds Affect Your True Advertising ROAS", desc: "Ad platforms usually report conversion value when the purchase happens.", href: "/resources/how-refunds-affect-your-true-advertising-roas" },
      { title: "Should Shipping Revenue Count Toward ROAS?", desc: "Whether shipping charged to the customer belongs in ROAS depends on what you want the revenue figure to represent.", href: "/resources/should-shipping-revenue-count-toward-roas" },
      { title: "Should Tax Be Included in Ecommerce ROAS?", desc: "Tax collected from the customer is usually money the business collects on behalf of a tax authority rather than economic revenue it gets to keep.", href: "/resources/should-tax-be-included-in-ecommerce-roas" },
      { title: "Should Creative Production Costs Be Included in CAC?", desc: "If creative production exists primarily to acquire customers, it belongs somewhere in the cost of acquisition.", href: "/resources/should-creative-production-costs-be-included-in-cac" },
      { title: "Why Revenue-Based ROAS Can Hide an Unprofitable Business", desc: "Revenue-based ROAS treats every dollar of sales as equally valuable.", href: "/resources/why-revenue-based-roas-can-hide-an-unprofitable" },
      { title: "Profit ROAS vs Revenue ROAS: Which Should You Use?", desc: "Revenue ROAS is easy to calculate and useful for campaign optimization.", href: "/resources/profit-roas-vs-revenue-roas-which-should-you-use" },
      { title: "How to Calculate Profit per Order From Paid Ads", desc: "Profit per paid order starts with the order value and subtracts the costs that order creates.", href: "/resources/how-to-calculate-profit-per-order-from-paid-ads" },
      { title: "What Is a Good Contribution Margin After Advertising?", desc: "There is no universal “good” contribution margin after ads because businesses have very different fixed costs, growth goals and repeat-customer economics.", href: "/resources/what-is-a-good-contribution-margin-after-advertising" },
      { title: "How to Decide Whether an Unprofitable Campaign Is Worth Keeping", desc: "An unprofitable campaign can be worth keeping if it creates future customer value, assists other profitable sales or is still inside a deliberate test.", href: "/resources/how-to-decide-whether-an-unprofitable-campaign-is" },
      { title: "Why Scaling Revenue Can Reduce Profit", desc: "Revenue can grow while profit falls when the next sales are more expensive to acquire or less profitable to fulfil.", href: "/resources/why-scaling-revenue-can-reduce-profit" },
    ],
  },
  {
    id: "tracking",
    label: "Tracking & Privacy",
    intro: "Consent, server-side tracking and the privacy changes that quietly move your conversion numbers.",
    items: [
      { title: "Consent Mode on Shopify: Why Google Ads Conversions May Change", desc: "What consent modeling actually does, and what it doesn't recover.", href: "/resources/google-consent-mode-shopify" },
      { title: "iOS, Ad Blockers and Privacy: How Much Shopify Tracking Are You Losing?", desc: "What ITP and ad blockers actually block, and what server-side tracking can and can't fix.", href: "/resources/ios-ad-blockers-shopify-tracking-loss" },
      { title: "How Shopify Server-Side Tracking Works", desc: "A technical guide covering architecture, deduplication, consent, testing and common implementation mistakes.", href: "/resources/shopify-server-side-tracking-guide" },
      { title: "Why More Accurate Tracking Doesn't Automatically Create More Sales", desc: "Better tracking can improve decisions, but it can't fix a weak product, bad offer or poor website by itself.", href: "/resources/does-better-tracking-improve-sales" },
      { title: "Can Server-Side Tracking Improve Ad Performance?", desc: "It can improve signal quality and resilience, but it doesn't guarantee lower CPA or higher revenue.", href: "/resources/can-server-side-tracking-improve-ad-performance" },
      { title: "Shopify Customer Events Explained for Marketers", desc: "Not the developer terminology: which customer actions are available and how your tracking tool consumes them.", href: "/resources/shopify-customer-events-explained" },
      { title: "Google Tag Manager vs Shopify Customer Events", desc: "GTM is a tag-management system; Customer Events is Shopify's own framework. That's why they aren't direct substitutes.", href: "/resources/google-tag-manager-vs-shopify-customer-events" },
      { title: "Should Shopify Stores Still Use Google Tag Manager?", desc: "It's no longer safe to assume every Shopify store needs GTM just because it's standard practice elsewhere.", href: "/resources/should-shopify-use-google-tag-manager" },
      { title: "How to Test a Shopify Purchase Event", desc: "One test order, checked across Meta, Google Ads, GA4 and attribution tools: the highest-value check after any tracking change.", href: "/resources/test-shopify-purchase-event" },
      { title: "Shopify Pixel vs Meta CAPI: Do You Need Both?", desc: "For most robust Meta tracking setups, browser Pixel and server-side CAPI are complementary rather than mutually exclusive.", href: "/resources/shopify-pixel-vs-meta-capi-do-you-need-both" },
      { title: "Google Tag Assistant Shows Multiple Google Tags: What Does It Mean?", desc: "Seeing multiple Google tags is not automatically an error.", href: "/resources/google-tag-assistant-shows-multiple-google-tags-what" },
      { title: "Shopify Theme Change Broke Tracking: What to Check", desc: "A theme change can remove scripts that were installed manually, alter page structure and expose tracking setups nobody realized depended on the old theme.", href: "/resources/shopify-theme-change-broke-tracking-what-to-check" },
      { title: "Shopify App Installation Changed Conversion Tracking: What Happened?", desc: "Marketing and analytics apps often install their own pixels, server events or customer-event integrations.", href: "/resources/shopify-app-installation-changed-conversion-tracking" },
    ],
  },
  {
    id: "email-retention",
    label: "Email & Retention",
    intro: "Klaviyo flows, repeat purchase rate and retention economics for Shopify stores running paid acquisition.",
    items: [
      { title: "How Much Revenue Should Email Marketing Generate for a Shopify Store?", desc: "Why there's no universal healthy percentage, and how to judge program health with Shopify as the revenue anchor.", href: "/resources/how-much-revenue-should-email-marketing-generate-ecommerce" },
      { title: "Klaviyo Revenue Looks Too High: Is Email Taking Too Much Credit?", desc: "Why attribution and causation are different, and how to check whether Klaviyo's number reconciles with Shopify and paid media.", href: "/resources/klaviyo-revenue-too-high" },
      { title: "Shopify vs Klaviyo Revenue Doesn't Match: Why?", desc: "Shopify records orders, Klaviyo reports attributed revenue. The two aren't designed to match, and here's when a gap is worth investigating.", href: "/resources/shopify-vs-klaviyo-revenue-doesnt-match" },
      { title: "Klaviyo Attribution Explained for Shopify Stores", desc: "How Klaviyo connects orders to email and SMS interactions, and why click attribution, view attribution and window length all change the number.", href: "/resources/klaviyo-attribution-explained" },
      { title: "Does Klaviyo Over-Attribute Revenue?", desc: "Why loyal customers and cross-channel overlap can make Klaviyo's revenue number look larger than the true incremental impact of email.", href: "/resources/does-klaviyo-over-attribute-revenue" },
      { title: "How to Measure the True Impact of Email Marketing", desc: "Platform metrics, Shopify outcomes, holdout tests, profit and list health: a fuller way to judge what email actually contributes.", href: "/resources/measure-email-marketing-true-impact-ecommerce" },
      { title: "Abandoned Cart Email vs Meta Retargeting: Which Should Get the Credit?", desc: "Both systems can legitimately claim a recovered cart. The right question is incremental recovery, not which dashboard gets credit.", href: "/resources/abandoned-cart-email-vs-retargeting-attribution" },
      { title: "How Many Abandoned Cart Emails Should a Shopify Store Send?", desc: "There's no universal reason every store needs exactly three messages. Here's how to build a sequence around objections and buying cycle instead.", href: "/resources/how-many-abandoned-cart-emails-shopify" },
      { title: "Browse Abandonment vs Cart Abandonment: What's the Difference?", desc: "The two happen at different levels of intent and need different messages, plus how to avoid overwhelming the same customer.", href: "/resources/browse-abandonment-vs-cart-abandonment" },
      { title: "Should You Offer a Discount in Your Abandoned Cart Emails?", desc: "A discount can recover carts or teach customers to abandon on purpose. Here's when an incentive is commercially sensible and how to cost it.", href: "/resources/should-abandoned-cart-emails-offer-discount" },
      { title: "Why Your Abandoned Cart Emails Get Clicks but No Sales", desc: "If people click and still don't buy, the email likely did its job. Here's what to check on the store side instead.", href: "/resources/abandoned-cart-emails-clicks-no-sales" },
      { title: "Shopify Abandoned Checkout vs Klaviyo Abandoned Cart: Why the Numbers Differ", desc: "The two systems count different abandonment stages and audiences. Here's how to compare event definitions before assuming something's broken.", href: "/resources/shopify-abandoned-checkout-vs-klaviyo-abandoned-cart" },
      { title: "How Much Should Ecommerce Brands Spend to Acquire a New Customer?", desc: "The allowable acquisition cost should come from contribution, repeat value and cash flow, not a benchmark.", href: "/resources/how-much-should-ecommerce-spend-to-acquire-customer" },
      { title: "First-Order Profit vs Lifetime Value: Which Should Drive Ad Spend?", desc: "First-order profit protects cash. LTV can justify growth, but only when cohort evidence actually supports it.", href: "/resources/first-order-profit-vs-lifetime-value-ecommerce" },
      { title: "How Long Can Ecommerce Brands Afford to Wait for Customer Payback?", desc: "A profitable customer can still create a cash-flow problem if it takes too long to recover the acquisition cost.", href: "/resources/ecommerce-cac-payback-period" },
      { title: "What Is CAC Payback Period in Ecommerce?", desc: "The time it takes for a new customer's contribution to recover the cost of acquiring them, with a worked example.", href: "/resources/cac-payback-period-ecommerce" },
      { title: "When Is It Okay to Lose Money on the First Shopify Order?", desc: "A sensible first-order loss requires evidence of repeat purchase rate and payback, not just an LTV assumption.", href: "/resources/lose-money-first-order-ecommerce" },
      { title: "How to Calculate Repeat Customer Value for a Shopify Store", desc: "A cohort method for turning repeat revenue into an expected repeat contribution you can use for acquisition targets.", href: "/resources/calculate-repeat-customer-value-shopify" },
      { title: "Why High Repeat Purchase Rate Changes Your Break-Even ROAS", desc: "The first order's math never changes. Retention changes how much the business is willing to invest to acquire it.", href: "/resources/repeat-purchase-rate-break-even-roas" },
      { title: "Customer Retention Rate vs Repeat Purchase Rate: What's the Difference?", desc: "Related metrics, different formulas: the definitions and cohort windows matter before comparing numbers.", href: "/resources/retention-rate-vs-repeat-purchase-rate-ecommerce" },
      { title: "Why Retention Can Matter More Than Improving Facebook Ads", desc: "Acquisition improvements have limits. Better retention makes every acquired customer worth more without touching Meta at all.", href: "/resources/ecommerce-retention-vs-acquisition" },
      { title: "Loyalty Program vs Discounts: Which Drives More Repeat Purchases?", desc: "Discounts move price. Loyalty builds accumulated value. Neither works if customers didn't like the first purchase.", href: "/resources/loyalty-program-vs-discounts-ecommerce" },
      { title: "Does Free Shipping Increase Customer Retention?", desc: "It can reduce remembered friction on reorders, but the product still has to earn the second purchase first.", href: "/resources/free-shipping-customer-retention-ecommerce" },
      { title: "How Much Should Ecommerce Brands Spend on Existing Customers?", desc: "There's no fixed percentage. Budget should follow incremental contribution, not a predetermined split.", href: "/resources/how-much-spend-on-existing-customers-ecommerce" },
      { title: "What Is a Good Abandoned Cart Recovery Rate?", desc: "Recovery rate depends on audience definition, price, buying cycle and attribution window. Your own baseline matters more than an external benchmark.", href: "/resources/good-abandoned-cart-recovery-rate-ecommerce" },
      { title: "Welcome Flow vs Campaigns: Where Should Ecommerce Brands Focus First?", desc: "If the store has steady new list growth, a strong welcome flow is one of the first email assets worth building because every future subscriber can experience it automatically.", href: "/resources/welcome-flow-vs-campaigns-where-should-ecommerce" },
      { title: "How Many Emails Should Be in a Shopify Welcome Flow?", desc: "A welcome flow should stop when it has said the important things, not when it reaches a template's recommended email count.", href: "/resources/how-many-emails-should-be-in-a-shopify-welcome-flow" },
      { title: "Should Your Welcome Flow Offer a Discount?", desc: "A welcome discount can accelerate a first purchase.", href: "/resources/should-your-welcome-flow-offer-a-discount" },
      { title: "Why Your Klaviyo Welcome Flow Isn't Converting", desc: "A welcome flow can fail because the emails are weak, but it can also fail because the subscribers themselves have little buying intent.", href: "/resources/why-your-klaviyo-welcome-flow-isn-t-converting" },
      { title: "How Often Should Ecommerce Brands Send Marketing Emails?", desc: "The correct email frequency is the highest cadence that continues to create incremental value without damaging list health and customer trust.", href: "/resources/how-often-should-ecommerce-brands-send-marketing-emails" },
      { title: "Are You Sending Too Many Marketing Emails?", desc: "You are sending too many emails when the marginal message creates less value than the fatigue it causes.", href: "/resources/are-you-sending-too-many-marketing-emails" },
      { title: "Email Open Rate Is High but Sales Are Low: What Does That Mean?", desc: "A high open rate tells you that the message was opened or at least recorded as opened.", href: "/resources/high-email-open-rate-low-sales" },
      { title: "Good Email Click Rate but No Sales: What to Check", desc: "If email recipients click and do not buy, stop optimizing the subject line.", href: "/resources/good-email-click-rate-but-no-sales-what-to-check" },
      { title: "How to Measure Email Profitability Instead of Just Revenue", desc: "Attributed email revenue is easy to celebrate.", href: "/resources/how-to-measure-email-profitability-instead-of-just" },
      { title: "What Is a Good Repeat Purchase Rate for Shopify?", desc: "A good repeat purchase rate depends heavily on what you sell.", href: "/resources/what-is-a-good-repeat-purchase-rate-for-shopify" },
      { title: "Why Your Shopify Store Gets Customers but Few Repeat Purchases", desc: "Strong first-order acquisition and weak retention can indicate that marketing is selling the first purchase more effectively than the product experience earns the second.", href: "/resources/why-your-shopify-store-gets-customers-but-few-repeat" },
      { title: "How to Increase Repeat Purchase Rate Without Constant Discounts", desc: "Discounts can create a second order quickly, but a retention strategy built entirely on cheaper prices becomes difficult to sustain.", href: "/resources/how-to-increase-repeat-purchase-rate-without-constant" },
      { title: "New Customers vs Returning Customers: Which Should You Optimize For?", desc: "A healthy ecommerce business usually needs both.", href: "/resources/new-customers-vs-returning-customers-which-should-you" },
      { title: "Why Returning Customer Revenue Can Make Your ROAS Look Better Than It Is", desc: "Returning customers often convert at a lower marketing cost because they already know and trust the brand.", href: "/resources/why-returning-customer-revenue-can-make-your-roas-look" },
      { title: "Should You Collect Email or SMS First on a Shopify Popup?", desc: "Email generally creates less signup friction.", href: "/resources/should-you-collect-email-or-sms-first-on-a-shopify" },
    ],
  },
  {
    id: "creative-offers",
    label: "Creative & Offers",
    intro: "Offer structure, discounting and creative testing systems for Meta and Google ecommerce campaigns.",
    items: [
      { title: "Are Constant Discounts Destroying Your Ecommerce Profitability?", desc: "A lower price can improve ROAS while every order contributes less money: the warning signs of promotion dependency.", href: "/resources/constant-discounts-ecommerce-profitability" },
      { title: "Should You Run Evergreen Discounts or Short Promotions?", desc: "Evergreen offers reduce friction, short promotions create urgency. Here's how to choose based on the job the offer needs to do.", href: "/resources/evergreen-discount-vs-limited-promotion-ecommerce" },
      { title: "Discount Code vs Automatic Discount: Which Converts Better?", desc: "Automatic discounts remove friction, codes give control over distribution. The better choice depends on how the promotion is meant to work.", href: "/resources/discount-code-vs-automatic-discount-shopify" },
      { title: "Free Shipping Threshold: How Should Shopify Stores Set It?", desc: "Building the threshold from current AOV, margin and shipping cost instead of copying a competitor's number.", href: "/resources/set-free-shipping-threshold-shopify" },
      { title: "How to Calculate a Profitable Free Shipping Threshold", desc: "A four-step model for testing whether a threshold's basket lift actually covers the shipping subsidy.", href: "/resources/calculate-profitable-free-shipping-threshold" },
      { title: "Should Your Free Shipping Threshold Be Above Your Current AOV?", desc: "Why order distribution and an achievable next item matter more than adding a flat percentage to AOV.", href: "/resources/free-shipping-threshold-above-aov" },
      { title: "Product Bundling vs Upselling: Which Is Better for Ecommerce?", desc: "Bundles package the decision before purchase, upsells preserve flexibility after it. Here's how to judge each by contribution per visitor.", href: "/resources/product-bundling-vs-upselling-ecommerce" },
      { title: "How to Price Ecommerce Bundles Without Destroying Margin", desc: "A bundle needs enough perceived value to justify buying more, not automatically a huge discount. Here's how to calculate the real saving.", href: "/resources/how-to-price-ecommerce-bundles" },
      { title: "Should You Advertise Your Best Seller or Highest-Margin Product?", desc: "Proven demand and acquisition room are different assets. Here's how to classify products by role instead of picking one metric.", href: "/resources/advertise-bestseller-or-high-margin-product" },
      { title: "Revenue vs Margin: Which Products Should You Scale With Ads?", desc: "A high-revenue SKU can be a weak scale candidate. Build allowable CPA and priorities from contribution, not the top line.", href: "/resources/scale-high-revenue-or-high-margin-products-ecommerce" },
      { title: "Product Bundles vs Discounts: Which Increase AOV?", desc: "Bundles often have better AOV potential than discounts, but only when the products genuinely belong together.", href: "/resources/product-bundles-vs-discounts-ecommerce" },
      { title: "How to Increase Shopify Average Order Value Without Hurting Conversion Rate", desc: "Raising AOV is only useful if customers still buy. An upsell strategy can leave revenue or profit unchanged.", href: "/resources/increase-shopify-average-order-value" },
      { title: "Should Ecommerce Stores Use Exit-Intent Popups?", desc: "A relevant last offer can recover value from a leaving visitor. A discount on every exit just teaches customers to fake one.", href: "/resources/exit-intent-popup-ecommerce" },
      { title: "Does a 10% Popup Discount Actually Increase Profit?", desc: "The right question isn't the signup rate. It's whether the incremental profit beats what the discount gives away.", href: "/resources/popup-discount-ecommerce-profitability" },
      { title: "Email Popup Conversion Rate: What Should Shopify Stores Expect?", desc: "A popup conversion rate is only useful once you understand what the visitor receives in exchange.", href: "/resources/ecommerce-popup-conversion-rate" },
      { title: "English Ads vs Local-Language Ads: Which Perform Better?", desc: "Local-language ads often improve relevance, but English can still work well in some categories and markets.", href: "/resources/english-ads-vs-local-language-ads" },
      { title: "Do Free Gifts Convert Better Than Percentage Discounts?", desc: "A free gift can create higher perceived value than an equivalent discount, especially when the gift feels relevant and desirable.", href: "/resources/do-free-gifts-convert-better-than-percentage-discounts" },
      { title: "Percentage Discount vs Fixed Discount: Which Works Better?", desc: "\"20% off\" and \"$20 off\" can represent the same economic value on a $100 order and feel different to the customer.", href: "/resources/percentage-discount-vs-fixed-discount-which-works" },
      { title: "Buy One Get One vs Percentage Discount for Ecommerce", desc: "Buy One Get One promotions encourage unit volume.", href: "/resources/buy-one-get-one-vs-percentage-discount-for-ecommerce" },
      { title: "Should You Show Competitor Price Comparisons on Product Pages?", desc: "Competitor comparisons can help when customers are actively evaluating alternatives.", href: "/resources/should-you-show-competitor-price-comparisons-on" },
      { title: "Does a Money-Back Guarantee Improve Shopify Conversion Rate?", desc: "A money-back guarantee can reduce the perceived risk of trying an unfamiliar product.", href: "/resources/does-a-money-back-guarantee-improve-shopify-conversion" },
      { title: "How Long Should an Ecommerce Guarantee Be?", desc: "There is no conversion rule saying 30 days is always worse than 60 or 90.", href: "/resources/how-long-should-an-ecommerce-guarantee-be" },
      { title: "Should Shopify Stores Offer Free Returns?", desc: "Free returns can reduce purchase risk, particularly for products where size, fit or appearance is difficult to judge online.", href: "/resources/should-shopify-stores-offer-free-returns" },
      { title: "Do Trust Badges Still Improve Ecommerce Conversion Rates?", desc: "Trust badges can reassure customers when they communicate something useful.", href: "/resources/do-trust-badges-still-improve-ecommerce-conversion" },
      { title: "Why Too Many Trust Badges Can Make a Store Look Less Trustworthy", desc: "Trust signals work best when they feel natural.", href: "/resources/why-too-many-trust-badges-can-make-a-store-look-less" },
      { title: "When Increasing Your Price Can Actually Improve Advertising Performance", desc: "Increasing price normally creates more purchase friction.", href: "/resources/when-increasing-your-price-can-actually-improve" },
      { title: "How Much Discount Is Too Much for Ecommerce?", desc: "A discount becomes too large when the incremental sales and customer value it creates no longer compensate for the margin you give away.", href: "/resources/how-much-discount-is-too-much-for-ecommerce" },
      { title: "How to Find New Meta Ad Angles Without Guessing", desc: "The best ad angles usually already exist in customer language.", href: "/resources/how-to-find-new-meta-ad-angles-without-guessing" },
      { title: "Where Should Ecommerce Brands Get Ideas for New Ad Creatives?", desc: "Good ad ideas come from the market more often than from other ads.", href: "/resources/where-should-ecommerce-brands-get-ideas-for-new-ad" },
      { title: "How to Turn Customer Objections Into High-Converting Ads", desc: "An objection is a reason a customer is interested but not yet comfortable buying.", href: "/resources/how-to-turn-customer-objections-into-high-converting" },
      { title: "Product Features vs Customer Benefits: What Should Ads Focus On?", desc: "Features explain what the product has.", href: "/resources/product-features-vs-customer-benefits-what-should-ads" },
      { title: "Should Ecommerce Ads Focus on Pain Points or Desired Outcomes?", desc: "Some products are bought to escape a problem.", href: "/resources/should-ecommerce-ads-focus-on-pain-points-or-desired" },
      { title: "How to Create Different Ad Angles for the Same Product", desc: "One product can solve several customer problems.", href: "/resources/how-to-create-different-ad-angles-for-the-same-product" },
      { title: "How Many Ad Angles Should You Test Before Changing the Offer?", desc: "There is no magic number of ad angles that proves an offer is bad.", href: "/resources/how-many-ad-angles-should-you-test-before-changing-the" },
      { title: "Why Testing New Creatives Won't Fix a Weak Offer", desc: "Creative determines how the product is presented.", href: "/resources/why-testing-new-creatives-won-t-fix-a-weak-offer" },
      { title: "How to Know Whether You Have a Creative Problem or an Offer Problem", desc: "Creative problems usually appear before or around the click.", href: "/resources/how-to-know-whether-you-have-a-creative-problem-or-an" },
      { title: "Why Your Best-Performing Ad May Not Be Your Best Creative", desc: "The ad with the most purchases may be your best commercial asset.", href: "/resources/why-your-best-performing-ad-may-not-be-your-best" },
      { title: "Meta Ads Hook Rate vs Sales: Which Matters More?", desc: "Sales matter more if the business objective is sales.", href: "/resources/meta-ads-hook-rate-vs-sales-which-matters-more" },
      { title: "Video Watch Time Is High but Sales Are Low: What Does That Tell You?", desc: "High watch time proves people were willing to watch.", href: "/resources/video-watch-time-is-high-but-sales-are-low-what-does" },
      { title: "How to Build an Ecommerce Creative Testing System That Produces Useful Learnings", desc: "Creative testing becomes expensive when every new ad is simply another piece of content.", href: "/resources/ecommerce-creative-testing-system" },
      { title: "How to Use Customer Reviews to Create Better Meta Ads", desc: "Reviews are useful creative research because customers describe the product after experiencing it, often in language the brand would never write.", href: "/resources/how-to-use-customer-reviews-to-create-better-meta-ads" },
    ],
  },
  {
    id: "marketing-agency",
    label: "Marketing & Agency",
    intro: "Deciding between in-house and an agency, what an engagement should actually include, and what it costs.",
    items: [
      { title: "Marketing Agency vs In-House: Which Is Better for Meta and Google Ads?", desc: "An honest comparison, including when in-house genuinely wins.", href: "/resources/marketing-agency-vs-in-house" },
      { title: "How Much Does an Ecommerce Marketing Agency Cost?", desc: "The common pricing structures and what actually moves the price.", href: "/resources/ecommerce-marketing-agency-cost" },
      { title: "Percentage of Ad Spend vs Fixed Fee: How Should a Marketing Agency Charge?", desc: "The incentive tradeoffs behind the two dominant pricing models.", href: "/resources/percentage-ad-spend-vs-flat-fee" },
      { title: "What Does a Meta Ads Agency Actually Do?", desc: "The real scope of the work, beyond campaign setup.", href: "/resources/what-does-a-meta-ads-agency-do" },
      { title: "What Does a Google Ads Agency Actually Do?", desc: "Account structure, feed oversight, tracking and reporting, explained.", href: "/resources/what-does-a-google-ads-agency-do" },
      { title: "How to Choose a Meta Ads Agency for Ecommerce", desc: "A genuine buyer's guide, not a ranked listicle.", href: "/resources/how-to-choose-a-meta-ads-agency" },
      { title: "How to Choose a Google Ads Agency for Ecommerce", desc: "What to ask about Shopping, PMax and feed experience specifically.", href: "/resources/how-to-choose-a-google-ads-agency" },
      { title: "Shopify-Specific Expertise vs a General Marketing Agency", desc: "What ecommerce-specific knowledge actually matters, and why.", href: "/resources/shopify-marketing-agency-vs-general-agency" },
      { title: "Meta Ads vs Google Ads for Shopify: Where to Spend First", desc: "How product type, AOV and buying cycle should shape the decision.", href: "/resources/meta-ads-vs-google-ads-shopify-budget" },
      { title: "How Much Should a Shopify Store Spend on Meta and Google Ads?", desc: "Building a budget from AOV, margin and target CPA instead of a rule of thumb.", href: "/resources/shopify-advertising-budget-how-much-to-spend" },
      { title: "When Should You Hire an Ecommerce Marketing Agency?", desc: "The signals worth acting on, and the ones that mean it's not the right move yet.", href: "/resources/when-to-hire-a-marketing-agency" },
      { title: "Your Ads Are Profitable: When Should You Increase the Budget?", desc: "Why a profitable campaign isn't automatically infinitely scalable.", href: "/resources/when-to-scale-ad-budget" },
      { title: "Should Advertising Agencies Optimize for ROAS or Profit?", desc: "An agency can influence ROAS directly through advertising.", href: "/resources/should-advertising-agencies-optimize-for-roas-or-profit" },
      { title: "Is a Meta Ads Agency Worth It?", desc: "A Meta Ads agency is worth it when the value of better decisions, execution and freed-up internal time exceeds the fee.", href: "/resources/is-a-meta-ads-agency-worth-it" },
      { title: "Is a Google Ads Agency Worth It?", desc: "A Google Ads agency becomes valuable when the account is important enough that search terms, Shopping feeds, bidding, tracking and budget decisions deserve specialist attention.", href: "/resources/is-a-google-ads-agency-worth-it" },
      { title: "Is an Ecommerce Marketing Agency Worth the Cost?", desc: "An ecommerce agency is worth the cost when it solves a problem more valuable than the fee.", href: "/resources/is-an-ecommerce-marketing-agency-worth-the-cost" },
      { title: "Freelancer vs Marketing Agency: Which Should Ecommerce Brands Hire?", desc: "A strong freelancer can outperform a weak agency, and a strong agency can provide capabilities one person cannot realistically cover.", href: "/resources/freelancer-vs-marketing-agency-which-should-ecommerce" },
      { title: "Small Marketing Agency vs Large Agency: Which Is Better?", desc: "Large agencies offer scale, established processes and deeper staffing.", href: "/resources/small-marketing-agency-vs-large-agency-which-is-better" },
      { title: "What Should You Expect From a Marketing Agency Every Month?", desc: "A good agency month should contain more than a report showing what happened.", href: "/resources/what-should-you-expect-from-a-marketing-agency-every" },
      { title: "How Often Should Your Marketing Agency Report to You?", desc: "Most ecommerce businesses benefit from a combination of short, frequent visibility and deeper monthly analysis.", href: "/resources/how-often-should-your-marketing-agency-report-to-you" },
      { title: "How Often Should You Meet With Your Marketing Agency?", desc: "Meeting more often does not automatically improve marketing.", href: "/resources/how-often-should-you-meet-with-your-marketing-agency" },
      { title: "Should Agency Fees Be Included in Your Marketing ROAS?", desc: "Platform ROAS should normally remain a simple campaign metric: attributed revenue divided by media spend.", href: "/resources/should-agency-fees-be-included-in-your-marketing-roas" },
      { title: "What Should Be Included in a Meta Ads Management Service?", desc: "Meta Ads management should cover more than turning campaigns on and off.", href: "/resources/what-should-be-included-in-a-meta-ads-management" },
      { title: "What Should Be Included in a Google Ads Management Service?", desc: "Google Ads management should cover the parts of the ecosystem that determine whether clicks become profitable customers.", href: "/resources/what-should-be-included-in-a-google-ads-management" },
    ],
  },
];

export function allResourceHrefs(): string[] {
  const core = CORE_GUIDES.map((g) => g.href);
  const articles = CATEGORIES.flatMap((c) => c.items.map((a) => a.href));
  return [...core, ...articles];
}
