"use client";

import Link from "next/link";
import ProductPageShell from "@/components/marketing/ProductPageShell";
import { Reveal } from "@/components/marketing/Reveal";
import Eyebrow from "@/components/marketing/Eyebrow";
import Breadcrumbs from "@/components/marketing/Breadcrumbs";
import { ManagedServicesCTA } from "@/components/marketing/CTAGroup";

const ARTICLE_JSON_LD = {
  "@context": "https://schema.org",
  "@type": "Article",
  "headline": "Profit ROAS vs Revenue ROAS: Which Should You Use?",
  "description": "Revenue ROAS is easy to calculate and useful for campaign optimization.",
  "datePublished": "2026-08-12",
  "dateModified": "2026-08-12",
  "author": {
    "@type": "Organization",
    "name": "Attribix",
    "url": "https://www.attribix.app"
  },
  "publisher": {
    "@type": "Organization",
    "name": "Attribix",
    "url": "https://www.attribix.app",
    "logo": {
      "@type": "ImageObject",
      "url": "https://www.attribix.app/assets/logo.svg"
    }
  },
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://www.attribix.app/resources/profit-roas-vs-revenue-roas-which-should-you-use"
  }
};

const BREADCRUMB_JSON_LD = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [
    {
      "@type": "ListItem",
      "position": 1,
      "name": "Home",
      "item": "https://www.attribix.app"
    },
    {
      "@type": "ListItem",
      "position": 2,
      "name": "Resources",
      "item": "https://www.attribix.app/resources"
    },
    {
      "@type": "ListItem",
      "position": 3,
      "name": "Profit ROAS vs Revenue ROAS",
      "item": "https://www.attribix.app/resources/profit-roas-vs-revenue-roas-which-should-you-use"
    }
  ]
};

export default function Page() {
  return (
    <ProductPageShell>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(ARTICLE_JSON_LD) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(BREADCRUMB_JSON_LD) }} />

      <section className="mx-auto max-w-3xl px-4 pt-24 pb-10 md:pt-32">
        <Reveal>
          <Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Resources", href: "/resources" }, { label: "Profit ROAS vs Revenue ROAS" }]} />
          <Eyebrow>Attribution & Analytics</Eyebrow>
          <h1 className="text-4xl sm:text-5xl md:text-6xl font-extrabold leading-[1.08] tracking-tight">
            Profit ROAS vs Revenue ROAS: Which Should You Use?
          </h1>
          <div className="mt-6 text-lg text-white/65 max-w-xl leading-relaxed space-y-3">
            <p className="text-white/60 leading-relaxed text-sm">
              Revenue ROAS is easy to calculate and useful for campaign optimization. Profit-based measures are closer to the business outcome but require better cost data.
            </p>
          </div>
        </Reveal>
      </section>

      <section className="mx-auto max-w-3xl px-4 py-10">
        <Reveal>
          <h2 className="text-2xl md:text-3xl font-extrabold mb-4">Revenue ROAS</h2>
          <div className="space-y-4">
          <p className="text-white/60 leading-relaxed text-sm">
            Attributed revenue ÷ ad spend.
          </p>
          <p className="text-white/60 leading-relaxed text-sm">
            It is simple, widely understood and available in ad platforms.
          </p>
          </div>
        </Reveal>
      </section>

      <section className="relative py-10">
        <div className="absolute inset-0 -z-10 bg-black/15" />
        <div className="mx-auto max-w-3xl px-4">
          <Reveal>
            <h2 className="text-2xl md:text-3xl font-extrabold mb-4">Profit/Contribution on ad spend</h2>
            <div className="space-y-4 max-w-2xl">
            <p className="text-white/60 leading-relaxed text-sm">
              A more economic version uses contribution generated by the orders rather than gross revenue.
            </p>
            <p className="text-white/60 leading-relaxed text-sm">
              Example:
            </p>
            <p className="text-white/60 leading-relaxed text-sm">
              Revenue: $50,000
            </p>
            <p className="text-white/60 leading-relaxed text-sm">
              Contribution before ads: $20,000
            </p>
            <p className="text-white/60 leading-relaxed text-sm">
              Ad spend: $10,000
            </p>
            <p className="text-white/60 leading-relaxed text-sm">
              Revenue ROAS = 5.0x.
            </p>
            <p className="text-white/60 leading-relaxed text-sm">
              Contribution-before-ad ratio = 2.0x; after ad spend, $10,000 contribution remains.
            </p>
            </div>
          </Reveal>
        </div>
      </section>

      <section className="mx-auto max-w-3xl px-4 py-10">
        <Reveal>
          <h2 className="text-2xl md:text-3xl font-extrabold mb-4">Which is better?</h2>
          <div className="space-y-4">
          <p className="text-white/60 leading-relaxed text-sm">
            Use revenue ROAS for fast campaign comparison when product margins are similar. Use contribution/profit measures when margins vary or business profitability drives budget decisions.
          </p>
          </div>
        </Reveal>
      </section>

      <section className="relative py-10">
        <div className="absolute inset-0 -z-10 bg-black/15" />
        <div className="mx-auto max-w-3xl px-4">
          <Reveal>
            <h2 className="text-2xl md:text-3xl font-extrabold mb-4">Data quality matters</h2>
            <div className="space-y-4 max-w-2xl">
            <p className="text-white/60 leading-relaxed text-sm">
              Profit optimization is only as good as COGS, refunds and variable-cost data. Do not replace a simple accurate metric with a sophisticated inaccurate one.
            </p>
            </div>
          </Reveal>
        </div>
      </section>

      <section className="mx-auto max-w-3xl px-4 py-10">
        <Reveal>
          <h2 className="text-xl md:text-2xl font-extrabold mb-4">Related reading</h2>
          <ul className="space-y-2 text-sm">
            <li><Link href="/resources/how-to-calculate-profit-per-order-from-paid-ads" className="text-cyan-300 underline underline-offset-4 hover:text-cyan-200">How to Calculate Profit per Order From Paid Ads</Link></li>
            <li><Link href="/resources/why-revenue-based-roas-can-hide-an-unprofitable" className="text-cyan-300 underline underline-offset-4 hover:text-cyan-200">Why Revenue-Based ROAS Can Hide an Unprofitable Business</Link></li>
            <li><Link href="/resources/what-is-a-good-contribution-margin-after-advertising" className="text-cyan-300 underline underline-offset-4 hover:text-cyan-200">What Is a Good Contribution Margin After Advertising?</Link></li>
          </ul>
        </Reveal>
      </section>

      <section className="mx-auto max-w-2xl px-4 py-20 text-center">
        <Reveal>
          <h2 className="text-2xl md:text-3xl font-extrabold">Not sure if ROAS is telling the full story?</h2>
          <p className="mt-4 text-white/60 max-w-lg mx-auto">
            If your products have very different margins and revenue ROAS sends budget toward the wrong items, contact us. We can help add a contribution layer.
          </p>
          <ManagedServicesCTA className="mt-8 justify-center" />
        </Reveal>
      </section>
    </ProductPageShell>
  );
}
